
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/will-y/crystal-tools/issues" #optional

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    # the modid of the dependency
    modId="neoforge" #mandatory
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[17,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    versionRange="[8,)"
    ordering="NONE"
    side="BOTH"