#Starting EXP Value for Tools and Armor
#Range: 1 ~ 10000
base_experience_cap = 75
#Max exp that can be required to get to the next level
#Range: 1 ~ 100000
max_exp = 1000
#Multiplier for the experience to the next level
#Range: 1.0 ~ 5.0
experience_multiplier = 1.1
#Multiplies how much experience Armor gets. (EXP_GAINED = DAMAGE_TAKEN * ARMOR_EXPERIENCE_BOOST)
#Range: 0.1 ~ 10000.0
armor_experience_boost = 2.0
#Multiplies how much experience Bows get. (EXP_GAINED = DAMAGE_DONE * BOW_EXPERIENCE_BOOST)
#Range: 0.1 ~ 10000.0
bow_experience_boost = 1.0
#Multiplies how much experience Swords get. (EXP_GAINED = DAMAGE_DONE * SWORD_EXPERIENCE_BOOST
#Range: 0.1 ~ 10000.0
sword_experience_boost = 0.8
#Determines how much experience rockets get when used
#Range: 1 ~ 100
rocket_experience_boost = 5
#Multiplies how much experience Apples get. (EXP_GAINED = EFFECTIVE_HUNGER_RESTORED * APPLE_EXPERIENCE_BOOST
#Range: 0.1 ~ 1000.0
apple_experience_boost = 0.5
#Multiplies how much experience Furnaces get.
#Range: 1.0 ~ 1000.0
furnace_experience_boost = 1.0
#Multiplies experience Tridents get. (EXP_GAINED = DAMAGE_DONE * TRIDENT_EXPERIENCE_BOOST
#Range: 0.1 ~ 10000.0
trident_experience_boost = 1.0
#Determines how much experience you get for fish caught
#Range: 1 ~ 1000
fishing_rod_exp = 10
#Determines the cooldown between tool auto repairs
#Range: 1 ~ 10000
tool_repair_cooldown = 300
#If true, tools will auto repair while you are holding them
repair_in_hand = false
#Increases the repair cooldown for the rocket
#Range: 1.0 ~ 10000.0
rocket_repair_modifier = 10.0
#Increases the repair cooldown for the apple
#Range: 1.0 ~ 10000.0
apple_repair_modifier = 50.0
#Determines the range of the vein miner on the shovel, pickaxe, and AIOT. It will mine blocks up to this range away from the ore broken.
#Range: 1 ~ 100
vein_miner_range = 4
#Determines the range of the tree chopper and tree stripper upgrade on the axe. It will mine logs up to this range away from the log broken.
#Range: 1 ~ 100
tree_chopper_range = 10
#The block texture to use for the background of the upgrade screen. Must be a vanilla block name.
upgrade_screen_background = "cracked_deepslate_tiles"
#Enables or disables item requirements for certain upgrades
enable_item_requirements = true
#Controls the opacity of the skill tree background
#Range: 0.0 ~ 1.0
background_opacity = 1.0
#If it is true then the skill tree screen pauses the game (in single-player), if false then it doesn't
pause_screen = true
#Require a crystal item in your inventory for resetting skill points
require_crystal_for_reset = true
#Disables the block highlighting for 3x3 mining
disable_block_target_rendering = false
#Reach distance increase for the Reach upgrade
#Range: 0.01 ~ 20.0
reach_increase = 0.5
#If true, Crystal Tools will be enchantable. Note: There could be some weird interactions / it might break some things
enchant_tools = false
#Number of levels in a tool before the experience level costs increases. Set to 0 to disable scaling
#Range: 0 ~ 100
experience_leveling_scaling = 10
#Determines the number of experience levels you need to gain a level on a tool. Set to 0 to disable
#Range: 0 ~ 100
experience_per_skill_level = 10
#Disables Crystal Pickaxe
disable_pickaxe = false
#Disables Crystal Shovel
disable_shovel = false
#Disables Crystal Axe
disable_axe = false
#Disables Crystal Sword
disable_sword = false
#Disables Crystal Hoe
disable_hoe = false
#Disables Crystal AIOT
disable_aiot = false
#Disables Crystal Bow
disable_bow = false
#Disables Crystal Rocket
disable_rocket = false
#Disables Crystal Trident
disable_trident = false
#Disables Crystal Fishing Rod
disable_fishing_rod = false
#Disables Crystal Elytra
disable_elytra = false
#Disables Crystal Helmet
disable_helmet = false
#Disables Crystal Chestplate
disable_chestplate = false
#Disables Crystal Leggings
disable_leggings = false
#Disables Crystal Boots
disable_boots = false
#Disables Crystal Apple
disable_apple = false
#Disables Crystal Backpack
disable_backpack = false
#Ticks added to fuel sources per level of fuel efficiency
#Range: 1 ~ 1000
fuel_efficiency_added_ticks = 100
#Ticks subtracted from the smelting time per level of furnace speed
#Range: 1 ~ 1000
speed_upgrade_subtract_ticks = 10
#Percentage increase for experience gained from smelting items. EXP_GAINED = EXP_IN_FURNACE * (1 + EXPERIENCE_BOOST_PERCENTAGE * EXPERIENCE BOOST LEVELS)
#Range: 0.0 ~ 1000.0
experience_boost_percentage = 0.10000000149011612
#Method used for sorting the Crystal Backpack
#Allowed Values: QUANTITY, NAME, MOD, ID
backpack_sort_type = "QUANTITY"
#Starting EXP Value for the Backpack
#Range: 1 ~ 10000
backpack_base_experience_cap = 150
#If true, channeling Crystal Tridents will summon lightning even if they don't hit an entity
always_channel = true

