license="${mod_license}"
issueTrackerURL="https://github.com/will-y/crystal-tools/issues" #optional

[[mods]]
modId="${core_id}"
version="${core_version}"
displayName="${core_name}"
authors="${mod_authors}"
description='''${core_description}'''

[[dependencies."${core_id}"]]
    # the modid of the dependency
    modId="neoforge" #mandatory
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${core_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${core_id}"]]
    modId="jei"
    type="optional"
    versionRange="[19,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies."${core_id}"]]
    modId="curios"
    type="optional"
    versionRange="[8,)"
    ordering="NONE"
    side="BOTH"